### ISSUE TITLE
Standard Distance plugin not creating a polygon file - only a point file

### ISSUE THREAD

**Issue by jkblackburn** [GuillemHerrera/StandardDistance#2]
Hello, I love that you have developed this plugin. However, when I try to run it and create an output, it is trying to create a point shapefile (or geopkg) and will not create a polygon. Any ideas? I am trying to use this for a class I teach. THANKS

jas

jkblackburn@ufl.edu

**Comment by GuillemHerrera** [comment]
Hi Jas, I'm glad you're using the plugin and that you find it interesting. I made some tests after your comment and I see that are a problem with source layers if it is a point layer. 

I will work to fix this problem.

Thanks for the report!

**Comment by GuillemHerrera** [comment]
Issue solved at 1.0.1 version.

Now available in Qgis Pluguins repository
