### ISSUE TITLE
Unexpected type 'int' ?

### ISSUE THREAD

**Issue by cmill629** [GuillemHerrera/StandardDistance#3]
Hi! I'm following along with an online course to learn QGIS (so I am incredibly new, only been at this for a few weeks), and I cannot get the Standard Distance plugin to work. I thought that the "unexpected type 'int'" meant there was an integer, but I exported out a layer that does not have any integers, and I am still receiving the same message.  

I've tried Googling, but I cannot find this same issue posted anywhere else. Any advice?

QGIS version: 3.34.1-Prizren
QGIS code revision: 133927424d
Qt version: 5.15.3
Python version: 3.9.5
GDAL version: 3.8.0
GEOS version: 3.12.1-CAPI-1.18.1
PROJ version: Rel. 9.3.0, September 1st, 2023
PDAL version: 2.6.0 (git-version: e4d82c)
Algorithm started at: 2023-12-27T09:59:02
Algorithm 'Standard Distance' starting…
Input parameters:
{ 'GBYFIELD' : '', 'INPUT' : '14365.shp', 'OUTPUT' : 'TEMPORARY_OUTPUT', 'WFIELD' : '' }

Traceback (most recent call last):
File "C:\Users/me/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\StandardDistance\StandardDistanceAlg.py", line 100, in processAlgorithm
(sink, dest_id) = self.parameterAsSink(
TypeError: QgsProcessingAlgorithm.parameterAsSink(): argument 5 has unexpected type 'int'

Execution failed after 0.01 seconds

Loading resulting layers
Algorithm 'Standard Distance' finished

**Comment by josxuo** [comment]
I'm experiencing the same issue. Cannot get the tool to calculate standard distance, seemingly no matter the input.

**Comment by GuillemHerrera** [comment]
Thanks @cmill629 and @josxuo for the report. Long time that I'm not using he plugin. 
Just upload a new version of the plugin with the issue fixed. Maybe we must wait some days to see updated in Qgis Plugins Repository.

I hope that the plugin can help you, and any other!
